### ISSUE TITLE
MailCore.framework can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by rgbworld** [vincedev/MailCoreSPM#1]
When I run my project, I receive an error/alert that says:
`MailCore.framework can't be opened because Apple cannot check it for malicious software.`

I am running the app via Xcode's standard "Run" option - which uses a 'debug' build configuration.
There are 2 buttons on the alert: `Show in Finder` and `OK`. If I press OK, the app still launches and works as expected.

How do I prevent the warning?

It appears to me that it is a code-signing/security issue wrt the nested framework. I am hoping that when I 'archive' and notarize with Apple that the warning will go away.

Thanks for any suggestions. I'll report whatever I find as I try to resolve.

**Comment by vincedev** [comment]
I got `MailCore.framework` to build both for `x86_64` and `arm64` by:
- manually clone repositories for `libetpan` and `libctemplate`, then checkout revisions found in build scripts, and build boths for both archs
- then clone `MailCore`, make framework target look for libraries where said dependencies are built
- then build `MailCore` for both archs

Hope that helps
