### ISSUE TITLE
Thank you! 😄

### ISSUE THREAD

**Issue by cliftonlabrum** [vincedev/MailCoreSPM#2]
I just wanted to say thank you for putting this together. You even went to the trouble to make it work with Swift Package Manager. Well done!

This works great on my M1 machine and so far MailCore seems to work. Awesome!

Thanks again!

**Comment by vikdenic** [comment]
@cliftonlabrum Any chance you are able to build for arm64 iOS simulators with this? It currently forces me to build on Rosetta and I'm trying to resolve it.
